@startuml

[*] --> IDLE

IDLE --> RECEIVE_COMMAND : !CMD
IDLE --> FORWARD_COMMAND : CMD_TICK

RECEIVE_COMMAND --> WAIT_COMMAND_INACTIVE : rx_i == 5

WAIT_COMMAND_INACTIVE --> WAIT_AFTER_COMMAND_INACTIVE : cksum ok

WAIT_AFTER_COMMAND_INACTIVE --> FORWARD_COMMAND : 1500 us

FORWARD_COMMAND --> RECEIVE_COMMAND_RESPONSE_LENGTH

RECEIVE_COMMAND_RESPONSE_LENGTH --> RECEIVE_WRITE_RESPONSE : rx_i > 1 && (CMD_WRITE_SECTOR || CMD_PUT_SECTOR)
RECEIVE_COMMAND_RESPONSE_LENGTH --> RECEIVE_TICK_RESPONSE : rx_i > 1 && CMD_TICK
RECEIVE_COMMAND_RESPONSE_LENGTH --> WAIT_COMMAND_ACK : rx_i > 1

WAIT_COMMAND_ACK --> SEND_COMMAND_DATA_RESPONSE : 250 us (?)

RECEIVE_WRITE_RESPONSE --> RECEIVE_DATA_TO_WRITE : rx_i > 4 && buffer[2] == 'c'

RECEIVE_DATA_TO_WRITE --> RECEIVE_COMMAND_RESPONSE_LENGTH2 : rx_i == sector_size + 2 && cksum ok

RECEIVE_COMMAND_RESPONSE_LENGTH2 --> SEND_COMMAND_DATA_RESPONSE : rx_i > 1

SEND_COMMAND_DATA_RESPONSE --> IDLE : --response_length == 0

RECEIVE_TICK_RESPONSE --> IDLE : rx_i > 5

@enduml
