#!/bin/sh

if [ -z "$1" ]; then
	echo "usage: `basename $0` RFCOMM-NUMBER [ARGS...]"
	exit 1
fi
n=$1
shift
java -jar `dirname $0`/target/sio2b_pc_assembly-3.0-bin.jar --serial-port=/dev/rfcomm$n "$@"
